var catalogue =[ 
    {   code : 1,
        nom : "Gommage masque éclat d'été",
        desc: "50 ml Soin 2 en 1 qui nourrit et gomme les impuretés en un seul geste.",
        prix: 294.00 ,
		image : "../Css/PRODUITS/M1.jpg"
    },
    {   code : 2,
        nom : "Pause de masque nourrissant",
        desc: "50 ml masque crème à la texture gourmande nourrit intensémment la peau pour un confort absolu.",
        prix: 291.00 ,
		image : "../Css/PRODUITS/M2.jpg"
    },
    {   code : 3,
        nom : "Pause de masque apaisant",
        desc: "50 ml masque lutte contre le stress cutané et les tiraillements, il protège, adoucit la peau et absorbe les impuretés pour une peau éclatante et radieuse.",
        prix: 282.00 ,
		image : "../Css/PRODUITS/M3.jpg"
    },
    {   code : 4,
        nom : "Pause de masque purifiantPause de masque purifiant",
        desc: "50 ml Masque à base d’argile verte et rhassoul, de gingembre et d’extraits d’arbre à thé qui clarifient le teint pour une peau saine et pure. ",
        prix: 288.00 ,
		image : "../Css/PRODUITS/M4.jpg"
    },
    {   code : 5,
        nom : "Emulsion fraîche crème visage",
        desc: "60 ml Une émulsion pleine de fraîcheur qui agit instantanément pour une sensation d’hydratation intense.",
        prix: 219.00 ,
		image : "../Css/PRODUITS/C1.jpg"
    },
    {   code : 6,
        nom : "Lèvres à aimer Baume nourrissant",
        desc: " 15 ml Des lèvres douces et veloutées avec ce baume aux actifs nourrissants et protecteurs.",
        prix:  99.00 ,
		image : "../Css/PRODUITS/B1.jpg"
    },
    {   code : 7,
        nom : "Lèvres à aimer Baume repulpant",
        desc: " 15 ml Une formulation exceptionnelle qui réunit les meilleurs actifs pour des lèvres repulpées, plus jeunes, plus lisses et nourries en profondeur.",
        prix: 102.00 ,
		image : "../Css/PRODUITS/B2.jpg"
    },
    {   code : 8,
        nom : "Lait d'Orient corps",
        desc: "250 ml Peaux sèches à légèrement sèches. Nutrition quotidienne et légère avec une pénétration instantanée.Idéal pour les femmes pressées.",
        prix: 230.00 ,
		image : "../Css/PRODUITS/L1.jpg"
    },
    {   code : 9,
        nom : "Flocons de Lait corps",
        desc: "Cette brume de lait légère hydrate et nourrit la peau tout en lui apportant un vent de fraîcheur parfumé.",
        prix: 204.00 ,
		image : "../Css/PRODUITS/L2.jpg"
    },
    {   code : 10,
        nom : "Crème délice d'Orient",
        desc: "Crème corps luxueuse de texture riche et dense.",
        prix: 264.00 ,
		image : "../Css/PRODUITS/C2.jpg"
    },
    {   code : 11,
        nom : "De mains en mains crème mains",
        desc: "Riche et fondante, la crème “De Mains en Mains“ apporte douceur et protection aux mains les plus sèches.",
        prix: 171.00 ,
		image : "../Css/PRODUITS/C3.jpg"
    },
    {   code : 12,
        nom : "Cocon fondant de karité beurre de karité",
        desc: "Pour une nutrition renforcée de la tête aux pieds, ce beurre de soin concentré est indispensable pour réparer et nourrir intensément la peau.",
        prix: 270.00 ,
		image : "../Css/PRODUITS/B3.jpg"
    },
    {   code : 13,
        nom : "Baume sensuel corporel",
        desc: "Baume sensuel nourrissant pour le corps à base d’huile d’argan.",
        prix: 360.00 ,
		image : "../Css/PRODUITS/B4.jpg"
    },
    {   code : 14,
        nom : "Douche Ancestrale gel douche",
        desc: "Pour plonger dans un océan de douceur et de senteurs Orientales mythiques.",
        prix:  186.00 ,
		image : "../Css/PRODUITS/G1.jpg"
    },
    {   code : 15,
        nom : "Savon invités 35 Gs",
        desc: "Parfait pour recevoir vos invités, ce savon de 35 Gs est composé d'huile d'argan.",
        prix:  9.00 ,
		image : "../Css/PRODUITS/S1.jpg"
    },
    {   code : 16,
        nom : "Savon exfoliant",
        desc: " ce savon exfoliant de 100 gs contient des micro particules exfoliantes entièrement naturelles.",
        prix:  39.00 ,
		image : "../Css/PRODUITS/S2.jpg"
    },
    {   code : 17,
        nom : "Shampooing nourrissant",
        desc: "Avec notre sélection inédite de shampooings naturel, première étape de votre rituel beauté pour de beaux cheveux, propres et soyeux. ",
        prix: 186.00 ,
		image : "../Css/PRODUITS/SH.jpg"
    },
    {   code : 18,
        nom : "Démêlant pour cheveux",
        desc: "Exaltez la beauté de votre chevelure avec nos après-shampooings, Secs, colorés, fins, frisés, pour tout type de cheveux.",
        prix:  167.00 ,
		image : "../Css/PRODUITS/D1.jpg"
    },
    {   code : 19,
        nom : "Démêlant très doux",
        desc: "Ce démêlant très doux donne aux cheveux une extraordinaire douceur, brillance et tenue.",
        prix: 165.00 ,
		image : "../Css/PRODUITS/D2.jpg"
    },
    {   code : 20,
        nom : "Sérum lissant",
        desc: "Pour garder des cheveux sains, brillants et faciles à coiffer.",
        prix: 258.00 ,
		image : "../Css/PRODUITS/SL.jpg"
    },
    {   code : 21,
        nom : "Baume boucles lumineuses",
        desc: "Mettez en valeur vos cheveux ondulés ou frisés avec ce baume pour cheveux. ",
        prix:  246.00 ,
		image : "../Css/PRODUITS/B5.jpg"
    },
    {   code : 22,
        nom : "Rhassoul aux extraits aromatiques argile",
        desc: " Argile magique provenant du moyen Atlas Marocain, le rhassoul absorbe toutes les impuretés.",
        prix:  99.00 ,
		image : "../Css/PRODUITS/R1.jpg"
    },
    {   code : 23,
        nom : "Argile Rhassoul naturel du Maroc",
        desc: "Pour un nettoyage quotidien sous la douche, il nettoie et purifie sans agresser la peau. 100% naturel",
        prix: 90.00 ,
		image : "../Css/PRODUITS/R2.jpg"
    },
    {   code : 24,
        nom : "Eau de rose",
        desc: "Possède des vertus adoucissantes, mélanger avec le Rhassoul pour le corps. ",
        prix: 159.00 ,
		image : "../Css/PRODUITS/R3.jpg"
    },
    {   code : 25,
        nom : "Sels de bain",
        desc: "les bains de sel de mer est l'un des traitements les plus anciens utilisés en cure thermale et en spa pour adoucir la peau et revitaliser le corps et l'esprit.",
        prix: 102.00 ,
		image : "../Css/PRODUITS/SE.jpg"
    },
	    {   code : 26,
        nom : "Gommage masque éclat d'été",
        desc: "50 ml Soin 2 en 1 qui nourrit et gomme les impuretés en un seul geste.",
        prix: 294.00 ,
		image : "../Css/PRODUITS/M1.jpg"
    },
    {   code : 27,
        nom : "Pause de masque nourrissant",
        desc: "50 ml masque crème à la texture gourmande nourrit intensémment la peau pour un confort absolu.",
        prix: 291.00 ,
		image : "../Css/PRODUITS/M2.jpg"
    },
  ]
   